# Generated by Django 2.0.1 on 2018-01-16 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='description',
            new_name='description_text',
        ),
        migrations.RenameField(
            model_name='thing',
            old_name='name',
            new_name='name_text',
        ),
    ]
