# Generated by Django 2.0.1 on 2018-01-16 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20180115_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='description_text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='thing',
            old_name='name_text',
            new_name='name',
        ),
    ]
