# Generated by Django 2.0.1 on 2018-01-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_auto_20180115_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thingtothing',
            name='child',
        ),
        migrations.RemoveField(
            model_name='thingtothing',
            name='parent',
        ),
        migrations.AddField(
            model_name='thing',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='_thing_children_+', to='campaign.Thing'),
        ),
        migrations.AddField(
            model_name='thing',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='_thing_parents_+', to='campaign.Thing'),
        ),
        migrations.DeleteModel(
            name='ThingToThing',
        ),
    ]
