# Generated by Django 2.0.1 on 2018-01-16 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_auto_20180115_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='parents',
        ),
    ]
