# Generated by Django 2.0.1 on 2018-01-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_remove_thing_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='children',
            field=models.ManyToManyField(blank=True, to='campaign.Thing'),
        ),
    ]
