# Generated by Django 2.0.1 on 2018-01-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0010_sample_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
