# Generated by Django 2.0.1 on 2018-03-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0011_auto_20180117_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='display_in_summary',
            field=models.BooleanField(default=False),
        ),
    ]
