# Generated by Django 2.0.1 on 2018-03-02 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0012_attribute_display_in_summary'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('thing', 'attribute')},
        ),
    ]
