# Generated by Django 2.0.1 on 2018-03-03 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0015_attribute_is_thing'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Thing')),
            ],
        ),
    ]
