# Generated by Django 2.0.4 on 2018-05-04 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0018_campaign_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomEncounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RandomEncounterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='randomencounter',
            name='random_encounter_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.RandomEncounterType'),
        ),
        migrations.AddField(
            model_name='randomencounter',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Thing'),
        ),
        migrations.AlterUniqueTogether(
            name='randomencounter',
            unique_together={('thing', 'random_encounter_type', 'name')},
        ),
    ]
