# Generated by Django 2.0.1 on 2018-05-04 02:48

from django.db import migrations


def load_basic_data(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    RandomEncounterType = apps.get_model('campaign', 'RandomEncounterType')

    RandomEncounterType.objects.using(db_alias).bulk_create([
        RandomEncounterType(name='Obstacle'),
        RandomEncounterType(name='Creature'),
        RandomEncounterType(name='NPC')
    ])


def delete_basic_data(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    RandomEncounterType = apps.get_model('campaign', 'RandomEncounterType')

    RandomEncounterType.objects.using(db_alias).filter(name='Obstacle').delete()
    RandomEncounterType.objects.using(db_alias).filter(name='Creature').delete()
    RandomEncounterType.objects.using(db_alias).filter(name='NPC').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0019_auto_20180504_1415'),
    ]

    operations = [
        migrations.RunPython(load_basic_data, delete_basic_data)
    ]
