# Generated by Django 2.0.4 on 2018-05-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0020_encounter_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='thing',
            unique_together={('campaign', 'name')},
        ),
    ]
