# Generated by Django 2.0.1 on 2018-05-21 13:47

from django.db import migrations

appearance_options = [
    'Thin',
    'Fat',
    'Muscular',
    'Tall',
    'Short',
    'Gaunt',
    'Attractive',
    'Frail',
    'Old',
    'Young',
    'Middle-aged',
    'Wiry',
    'Has piercings',
    'Has facial scar',
    'Blind',
    'Tattooed',
    'Bald',
    'Dyed hair',
    'Unusual hairstyle'
]

personality_options = [
    'Friendly',
    'Grumpy',
    'Grim',
    'Cheerful',
    'Sarcastic',
    'Argumentative',
    'Rude',
    'Honest',
    'Helpful',
    'Arrogant',
    'Quiet',
    'Irritable',
    'Curious',
    'Critical',
    'Tired',
    'Energetic'
]

race_options = [
    'Dragonborn',
    'Dwarf',
    'Elf',
    'Tiefling',
    'Gnome',
    'Goliath',
    'Half-elf',
    'Halfling',
    'Half-orc',
    'Human',
    'Tabaxi',
    'Tortle'
]

occupation_type_options = [
    'Countryside',
    'Village',
    'City',
    'Military',
    'Seafaring'
]

occupation_options = [
    {
        'name': 'Countryside',
        'options': [
            'Hunter',
            'Trapper',
            'Hermit',
            'Druid',
            'Witch',
            'Wanderer',
            'Pilgrim'
        ]
    },
    {
        'name': 'Village',
        'options': [
            'Hunter',
            'Trapper',
            'Hermit',
            'Druid',
            'Witch',
            'Wanderer',
            'Pilgrim',
            'Woodsman',
            'Priest',
            'Trader',
            'Farmer',
            'Baker',
            'Craftsman'
        ]
    },
    {
        'name': 'City',
        'options': [
            'Hunter',
            'Trapper',
            'Hermit',
            'Druid',
            'Witch',
            'Wanderer',
            'Pilgrim',
            'Woodsman',
            'Priest',
            'Trader',
            'Farmer',
            'Baker',
            'Craftsman',
            'Guard',
            'Bounty hunter',
            'Artisan',
            'Builder',
            'Crime boss',
            'Smuggler',
            'Thief',
            'Hangman',
            'Caravan Leader',
            'Bard',
            'Circus Performer',
            'Magician',
            'Soldier',
            'Beggar',
            'Urchin',
            'Jeweler',
            'Smith',
            'Banker',
            'Noble'
        ]
    },
    {
        'name': 'Military',
        'options': [
            'Scout',
            'Archer',
            'Siege Engineer',
            'Spy',
            'Wizard',
            'Infantry',
            'Cavalry',
            'Officer',
            'Smith'
        ]
    },
    {
        'name': 'Seafaring',
        'options': [
            'Merchant Sailor',
            'Fisherman',
            'Diver',
            'Naval Sailor',
            'Merchant Captain',
            'Naval Captain',
            'Pirate',
            'Pirate Captain',
            'Whaler',
            'Explorer'
        ]
    }
]


def load_basic_data(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    NpcAppearance = apps.get_model('campaign', 'NpcAppearance')
    NpcPersonalityTrait = apps.get_model('campaign', 'NpcPersonalityTrait')
    NpcRace = apps.get_model('campaign', 'NpcRace')
    NpcOccupationType = apps.get_model('campaign', 'NpcOccupationType')
    NpcOccupation = apps.get_model('campaign', 'NpcOccupation')

    appearance_objects = [NpcAppearance(name=a) for a in appearance_options]
    NpcAppearance.objects.using(db_alias).bulk_create(appearance_objects)

    personality_objects = [NpcPersonalityTrait(name=p) for p in personality_options]
    NpcPersonalityTrait.objects.using(db_alias).bulk_create(personality_objects)

    race_objects = [NpcRace(name=r) for r in race_options]
    NpcRace.objects.using(db_alias).bulk_create(race_objects)

    occupation_type_objects = [NpcOccupationType(name=t) for t in occupation_type_options]
    NpcOccupationType.objects.using(db_alias).bulk_create(occupation_type_objects)

    occupation_objects = []
    for t in occupation_options:
        occupation_type = NpcOccupationType.objects.get(name=t['name'])
        for o in t['options']:
            occupation_objects.append(NpcOccupation(occupation_type=occupation_type, name=o))

    NpcOccupation.objects.using(db_alias).bulk_create(occupation_objects)


def delete_basic_data(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    NpcAppearance = apps.get_model('campaign', 'NpcAppearance')
    NpcPersonalityTrait = apps.get_model('campaign', 'NpcPersonalityTrait')
    NpcRace = apps.get_model('campaign', 'NpcRace')
    NpcOccupationType = apps.get_model('campaign', 'NpcOccupationType')

    for a in appearance_options:
        NpcAppearance.objects.using(db_alias).filter(name=a).delete()

    for p in personality_options:
        NpcPersonalityTrait.objects.using(db_alias).filter(name=p).delete()

    for r in race_options:
        NpcRace.objects.using(db_alias).filter(name=r).delete()

    for t in occupation_type_options:
        NpcOccupationType.objects.using(db_alias).filter(name=t).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0022_auto_20180521_1438'),
    ]

    operations = [
        migrations.RunPython(load_basic_data, delete_basic_data)
    ]
