# Generated by Django 2.0.4 on 2018-05-23 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0023_npc_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='NpcName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('npc_race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.NpcRace')),
            ],
        ),
    ]
