# Generated by Django 2.0.4 on 2018-05-23 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0024_npcname'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='npcname',
            unique_together={('name', 'npc_race')},
        ),
    ]
