# Generated by Django 2.0.4 on 2018-05-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0025_auto_20180522_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npcname',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
