# Generated by Django 2.0.4 on 2018-05-24 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0026_auto_20180522_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomizerAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('thing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.ThingType')),
            ],
        ),
        migrations.CreateModel(
            name='RandomizerAttributeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.RandomizerAttribute')),
            ],
        ),
        migrations.CreateModel(
            name='RandomizerAttributeCategoryOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.RandomizerAttributeCategory')),
            ],
        ),
        migrations.CreateModel(
            name='RandomizerAttributeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.RandomizerAttribute')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='randomizerattributeoption',
            unique_together={('name', 'attribute')},
        ),
        migrations.AlterUniqueTogether(
            name='randomizerattributecategoryoption',
            unique_together={('name', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='randomizerattributecategory',
            unique_together={('name', 'attribute')},
        ),
        migrations.AlterUniqueTogether(
            name='randomizerattribute',
            unique_together={('name', 'thing_type')},
        ),
    ]
