# Generated by Django 2.0.4 on 2018-05-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0027_auto_20180523_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomizerattributecategory',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
