# Generated by Django 2.0.4 on 2018-05-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0028_randomizerattributecategory_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomizerattributecategory',
            name='can_combine_with_self',
            field=models.BooleanField(default=False),
        ),
    ]
