# Generated by Django 2.0.4 on 2018-05-25 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0030_auto_20180524_2106'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='randomizerattributecategorysynonym',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='randomizerattributecategorysynonym',
            name='category',
        ),
        migrations.DeleteModel(
            name='RandomizerAttributeCategorySynonym',
        ),
    ]
