# Generated by Django 2.0.4 on 2018-05-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0031_auto_20180524_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomizerattributecategory',
            name='name_synonym_first',
        ),
        migrations.RemoveField(
            model_name='randomizerattributecategory',
            name='name_synonym_last',
        ),
    ]
