# Generated by Django 2.0.4 on 2018-05-25 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0033_randomizerattribute_concatenate_results'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NpcAppearance',
        ),
        migrations.AlterUniqueTogether(
            name='npcname',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='npcname',
            name='npc_race',
        ),
        migrations.AlterUniqueTogether(
            name='npcoccupation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='npcoccupation',
            name='occupation_type',
        ),
        migrations.DeleteModel(
            name='NpcPersonalityTrait',
        ),
        migrations.DeleteModel(
            name='NpcName',
        ),
        migrations.DeleteModel(
            name='NpcOccupation',
        ),
        migrations.DeleteModel(
            name='NpcOccupationType',
        ),
        migrations.DeleteModel(
            name='NpcRace',
        ),
    ]
