# Generated by Django 2.0.4 on 2018-05-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0034_auto_20180525_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomizerattributecategory',
            name='max_options_to_use',
            field=models.IntegerField(default=1),
        ),
    ]
