# Generated by Django 2.0.4 on 2018-05-26 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0035_randomizerattributecategory_max_options_to_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('randomizer_attribute_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.RandomizerAttributeCategory')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Thing')),
            ],
        ),
    ]
