# Generated by Django 2.0.4 on 2018-05-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0036_randomattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomizerattribute',
            name='can_randomize_later',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='randomizerattributecategory',
            name='can_randomize_later',
            field=models.BooleanField(default=False),
        ),
    ]
