# Generated by Django 2.0.4 on 2018-05-28 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0037_auto_20180527_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratorObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('thing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.ThingType')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratorObjectContains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_objects', models.IntegerField(default=1)),
                ('max_objects', models.IntegerField(default=5)),
                ('contained_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contained_object', to='campaign.GeneratorObject')),
                ('generator_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generator_object', to='campaign.GeneratorObject')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratorObjectFieldToRandomizerAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('generator_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.GeneratorObject')),
                ('randomizer_attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.RandomizerAttribute')),
                ('randomizer_attribute_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.RandomizerAttributeCategory')),
            ],
        ),
    ]
