# Generated by Django 2.0.4 on 2018-05-28 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0038_generatorobject_generatorobjectcontains_generatorobjectfieldtorandomizerattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatorobjectfieldtorandomizerattribute',
            name='randomizer_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.RandomizerAttribute'),
        ),
        migrations.AlterField(
            model_name='generatorobjectfieldtorandomizerattribute',
            name='randomizer_attribute_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.RandomizerAttributeCategory'),
        ),
    ]
