# Generated by Django 2.0.4 on 2018-05-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0039_auto_20180527_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatorobject',
            name='attribute_for_container',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
