# Generated by Django 2.0.4 on 2018-05-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0040_generatorobject_attribute_for_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomizerattributecategory',
            name='must_be_unique',
            field=models.BooleanField(default=True),
        ),
    ]
