# Generated by Django 2.0.4 on 2018-05-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0041_randomizerattributecategory_must_be_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatorobjectfieldtorandomizerattribute',
            name='field_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
