# Generated by Django 2.0.4 on 2018-05-30 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0042_auto_20180529_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatorobject',
            name='inherit_settings_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.GeneratorObject'),
        ),
    ]
