# Generated by Django 2.0.4 on 2018-05-30 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0043_generatorobject_inherit_settings_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomizerattribute',
            name='category_parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.RandomizerAttribute'),
        ),
    ]
