# Generated by Django 2.0.4 on 2018-05-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0044_randomizerattribute_category_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomizerattributecategory',
            name='use_values_from',
            field=models.ManyToManyField(blank=True, null=True, related_name='_randomizerattributecategory_use_values_from_+', to='campaign.RandomizerAttributeCategory'),
        ),
    ]
