# Generated by Django 2.0.4 on 2018-05-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0045_randomizerattributecategory_use_values_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomizerattributecategory',
            name='use_values_from',
            field=models.ManyToManyField(blank=True, to='campaign.RandomizerAttributeCategory'),
        ),
    ]
