# Generated by Django 2.0.4 on 2018-05-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0046_auto_20180530_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomizerattribute',
            name='must_be_unique',
            field=models.BooleanField(default=True),
        ),
    ]
