# Generated by Django 2.0.4 on 2018-05-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0047_randomizerattribute_must_be_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatorobject',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
