# Generated by Django 2.0.4 on 2018-05-31 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0048_auto_20180531_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomattribute',
            name='randomizer_attribute_category',
        ),
    ]
