# Generated by Django 2.0.4 on 2018-05-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0049_remove_randomattribute_randomizer_attribute_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomizerattributeoption',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
