# Generated by Django 2.0.4 on 2018-05-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0051_auto_20180531_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightpreset',
            name='attribute_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='weightpreset',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='weightpreset',
            unique_together={('name', 'attribute_name', 'campaign')},
        ),
    ]
