# Generated by Django 2.0.4 on 2018-06-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0052_auto_20180531_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='thing',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
