# Generated by Django 2.0.4 on 2018-06-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0054_randomizerattribute_max_options_to_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatorobjectcontains',
            name='percent_chance_for_one',
            field=models.IntegerField(default=0),
        ),
    ]
