# Generated by Django 2.0.4 on 2018-12-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0055_generatorobjectcontains_percent_chance_for_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
