# Generated by Django 2.0.4 on 2018-12-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0056_thing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thing',
            name='current_state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
