# Generated by Django 2.0.4 on 2018-12-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0057_auto_20181211_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
