# Generated by Django 2.0.4 on 2020-09-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0058_attribute_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='markup_background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thing',
            name='markup_current_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thing',
            name='markup_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
