# Generated by Django 2.0.4 on 2020-09-24 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0059_auto_20200924_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='DndBeyondRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DndBeyondType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('base_url', models.CharField(max_length=50)),
                ('markup_symbol', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='dndbeyondref',
            name='dndbeyond_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.DndBeyondType'),
        ),
        migrations.AlterUniqueTogether(
            name='dndbeyondref',
            unique_together={('dndbeyond_type', 'name')},
        ),
    ]
